FROM redis:latest
LABEL org.opencontainers.image.authors="spamblackhole.tommy@gmail.com"
LABEL org.opencontainers.image.source="https://github.com/tommynsong/pc_dashboard/tree/main/pc-cache"
LABEL org.opencontainers.image.vendor="focer"